## Numpy

NumPy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematicsl functions to operate on these data structures.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## create array using numpy

## create 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
## reshape to 2 d

arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns



array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4,5,]])
print(arr2.shape)

(1, 5)


In [10]:
arr3=np.array([[1,2,3,4,5],[1,2,3,4,5]]) ##2d array
print(arr3.shape)
print(arr3)



(2, 5)
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [14]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
## identity mattrix - all diagonal matrix 1

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
## Attributes of numpy array

arr4=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr4)
print("Array shape:\n",arr4.shape)
print("No of dimensions:\n",arr4.ndim)
print("Array size / no of elements:\n",arr4.size)
print("Array datatype:\n",arr4.dtype)
print("Array item size (in bytes):\n",arr4.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Array shape:
 (2, 3)
No of dimensions:
 2
Array size / no of elements:
 6
Array datatype:
 int64
Array item size (in bytes):
 8


In [22]:
## Numpy vectorized operation

arr5=np.array([1,2,3,4,5])
arr6=np.array([10,20,30,40,50])

## element wise addition
print("Addition",arr5+arr6)

## element wise sub
print("substraction",arr5-arr6)

## element wise mul
print("multiplication",arr5*arr6)

## element wise division
print("division",arr5/arr6)

Addition [11 22 33 44 55]
substraction [ -9 -18 -27 -36 -45]
multiplication [ 10  40  90 160 250]
division [0.1 0.1 0.1 0.1 0.1]


In [23]:
## universal function

arr7=np.array([2,3,4,5,6])

print(np.sqrt(arr7))
print(np.exp(arr7))
print(np.sin(arr7))
print(np.log(arr7))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
## Array slicing and indexing

arr8=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array\n",arr8)

Array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr8[0]

array([1, 2, 3, 4])

In [27]:
print(arr8[0][0])

1


In [28]:
arr8[2:] #2nd index means 3rd row onwards

array([[ 9, 10, 11, 12]])

In [30]:
arr8[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
arr8[1:,2:] ## 1st index onwards for row and 2nd index onwards for column

array([[ 7,  8],
       [11, 12]])

In [34]:
arr8[0:2,2:]

array([[3, 4],
       [7, 8]])

In [35]:
## modify array elements

arr8[0,0]=100

In [37]:
arr8[0][0]=1001

In [38]:
arr8

array([[1001,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

In [39]:
arr8[1:]=200

In [40]:
arr8

array([[1001,    2,    3,    4],
       [ 200,  200,  200,  200],
       [ 200,  200,  200,  200]])

In [41]:
## statistical concepts- normalization
## to have mean of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])

## calculate mean and standard deviation

mean=np.mean(data)
std_dev=np.std(data)


##normalize the data

norm_data=(data-mean)/std_dev

print("normalised data:",norm_data)



normalised data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [42]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

print("mean:",np.mean(data))
print("median:",np.median(data))
print("std_dev:",np.std(data))
print("variance:",np.var(data))

mean: 5.5
median: 5.5
std_dev: 2.8722813232690143
variance: 8.25


In [43]:
## logical operations
data=np.array([1,2,3,4,5,6,7,8,9,10])


data>5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [44]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [49]:
data[(data>5) & (data<8)]

array([6, 7])